# Generated by Django 2.2.19 on 2022-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220818_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                upload_to='posts/',
                verbose_name='Картинка'
            ),
        ),
    ]
